apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
    spec:
      containers:
      - name: reverse-proxy
        image: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
            - name: nginx-ssl-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-ssl-config
              mountPath: /etc/nginx/ssl-certs/cert.pem
              subPath: cert.pem
            - name: nginx-ssl-config
              mountPath: /etc/nginx/ssl-certs/key.pem
              subPath: key.pem

      volumes:
      - name: nginx-ssl-config
        configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
              - key: cert.pem
                path: cert.pem
              - key: key.pem
                path: key.pem
