apiVersion: v1
kind: Service
metadata:
  name: publish-website
spec:
  selector:
    name: web
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
