apiVersion: v1
kind: Service
metadata:
  name: python-service

spec:
  selector:
    name: python-pod
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
    nodePort: 30800
