apiVersion: v1
kind: Service
metadata:
  name: python-web-service
  labels:
    name: python-web-service
spec:
  selector:
    app: python-web
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
