apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: python-web-service-ingress

spec:
  rules:
    - host: python.web.svc
      http:
        paths:
        - path: /
          backend:
            serviceName: python-web-service
            servicePort: 80