apiVersion: v1
kind: Pod

metadata:
  name: website
  labels:
    name: web

spec:
  containers:
    - name: web-server
      image: nginx
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
