apiVersion: v1
kind: Pod
metadata:
  name: python-pod
  labels:
    name: python-pod

spec:
  containers:
    - name: python
      image: python:3.8
      command: ["python3"]
      args: ["-m", "http.server"]
      ports:
        - name: http
          containerPort: 8000

